### ISSUE TITLE
 Encountered a problem while running OFA prediction

### ISSUE THREAD

**Issue by nightforwar** [BennyTMT/LLMsForTimeSeries#3]
Traceback (most recent call last):
  File 'main.py', line 201, in <module>
    for i, (batch_x, batch_y, batch_x_mark, batch_y_mark) in tqdm(enumerate(train_loader)):
      raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>

Please let me know how to solve this issue. Thank you!

**Comment by nightforwar** [comment]
i have tried ETT ，it can work ，but weather、illness have this problem

**Comment by BennyTMT** [comment]
Thanks for your interest, a quick fix is to add string "ofa" in each shell script "model_id" field, like below

` --model_id 'ofa_weather_'$seq_len'_'$pred_len'_'$method `

(because we set up our simple methods in OFA as well, so it is a bit confused.)
we will update our script as well.

**Comment by nightforwar** [comment]
> Thanks for your interest, a quick fix is to add string "ofa" in each shell script "model_id" field, like below
> 
> `--model_id 'ofa_weather_'$seq_len'_'$pred_len'_'$method`
> 
> (because we set up our simple methods in OFA as well, so it is a bit confused.) we will update our script as well.

Thanks for your reply！
I am a first-year master's student, and in fact, this is my first time trying to reproduce code. May I ask if the pre-trained model weights are not provided, and if I have to train them myself? Thank you for your response!

**Comment by beyondguo** [comment]
pre-trained model weights can be downloaded from open-source platforms like huggingface. try to search for it
