### ISSUE TITLE
I am confused

### ISSUE THREAD

**Issue by nightforwar** [BennyTMT/LLMsForTimeSeries#4]
Thank you for the article. I have reproduced some of the results, and I plan to present this paper at the group meeting next week. However, I have some questions. After reading it, I feel a bit confused. It seems that after removing the LLM, the model is just a simple linear layer, yet the prediction performance is even better. It even outperforms some more complex architectures, such as Transformers or MLP-based models like TimesNet. This is quite difficult to understand. Why hasn’t anyone used a simple linear layer to achieve these results before? Thanks to the authors!

**Comment by nightforwar** [comment]
Thank you for the article. I have reproduced some of the results, and I plan to present this paper at the group meeting next week. However, I have some questions. After reading it, I feel a bit confused. It seems that after removing the LLM, the model is just a simple linear layer, yet the prediction performance is even better. It even outperforms some more complex architectures, such as Transformers or MLP-based models like TimesNet. This is quite difficult to understand. Why hasn’t anyone used a simple linear layer to achieve these results before? Thanks to the authors!

**Comment by BennyTMT** [comment]
There is a highly influential paper that might be helpful to you.
"Are Transformers Effective for Time Series Forecasting?"

From my personal experience, Patching is also a very useful technique and a key contributor to performance. please refer to the final section in our paper
