### ISSUE TITLE
The difference between PAttn and Patchtst

### ISSUE THREAD

**Issue by hvlgo** [BennyTMT/LLMsForTimeSeries#5]
Hello, I have read the implementation of PAttn and I am very confused about the difference between PAttn and Patchtst. It seems that PAttn is Patchtst with one layer attention block, which in a sense is exactly the same as patchtst.

**Comment by BennyTMT** [comment]
**Excellent question!**  

The main difference between PAttn and PatchTST is that we gradually removed parts of the Transformer module that may not be as essential, and Position Embedding, so we are not just PatchTST + Attention as you said. 

The motivation is quite similar to DLinear—we aimed to create a simple baseline, even if it could easily be outperformed. Many methods (like based on LLMs) are already surpassing DLinear.

As patching becomes widely applied, we designed a new "DLinear" based on Patching. 
(We actually even tried removing Attention, but it seems that patching and attention are naturally connected. Without Attention, the slicing loses its meaning.)

Before DLinear was proposed, "Decomposition" and "Linear" were already widely used in time series. Similarly, PAttn builds on the work of others and does not bring much model innovation.  Its significance lies in this: if you cannot outperform such a new simple method, you should reconsider the necessity of the new approach.

**Comment by hvlgo** [comment]
Thank you, I understand your idea. Good job!
